### ISSUE TITLE
Fix `kubectl` Connection Error in GitHub Actions Pipeline

### ISSUE THREAD

**Issue by rsubramani** [rsubramani/distributed-task-scheduler#4]
### Description
Currently, the GitHub Actions pipeline is failing at the step where it tries to apply the Kubernetes deployment using kubectl. The error message indicates that kubectl is attempting to connect to localhost:8080, which results in a connection refused error.

The issue seems to be that kubectl is not properly configured to connect to the Kubernetes cluster in the pipeline, and it's defaulting to the localhost, where there is no running Kubernetes API server.

### Error Message
```sql
E0925 05:49:33.386608    2586 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
unable to recognize "kubernetes/deployment.yaml": Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```

### Tasks

- [ ]  Store the kubeconfig as a GitHub secret (e.g., KUBECONFIG_CONTENT).
- [ ] Update the GitHub Actions workflow to use the correct kubeconfig for the Kubernetes cluster
- [ ]  Test the connection locally using kubectl to ensure the configuration is correct.
- [ ] Ensure that the Kubernetes cluster is reachable from GitHub Actions during the deployment step.

### Acceptance Criteria

- The GitHub Actions pipeline should successfully apply the Kubernetes deployment without kubectl connection errors.
- Ensure that kubectl is properly configured to communicate with the correct Kubernetes API server during the pipeline run.
